#!/bin/bash
source /usr/lib/elive-tools/functions
el_make_environment
. gettext.sh
TEXTDOMAIN="elive-extra-features"
export TEXTDOMAIN


main(){
    # pre {{{
    local ret depends

    guitool="/usr/bin/zenity --window-icon=/usr/share/icons/Elive/scalable/apps/logo-elive.png"

    # Usage
    if [[ "$UID" != 0 ]] ;then
        #echo -e "Usage: $(basename $BASH_SOURCE) "
        el_error "root privileges required"
        exit 1
    fi




    # }}}


    depends="pipelight-multi iceweasel"

    urxvt -T 'Installing Dependencies' -e bash -c "
set -e
source /usr/lib/elive-tools/functions
el_aptget_update
apt-get -f install
echo
echo

if ! apt-get install -y $depends 2>/dev/null ; then
    el_aptget_update force
    if ! apt-get install -y $depends ; then
        apt-get -f install

        el_aptget_update force
        apt-get install $depends
    fi
fi
echo

# do not ask for something already asked
#sed -i 's|^ACCEPTALL=0|ACCEPTALL=1|g' /usr/bin/pipelight-plugin

pipelight-plugin --accept --update


pipelight-plugin --accept --enable silverlight
pipelight-plugin --accept --create-mozilla-plugins
pipelight-plugin --accept --enable silverlight

touch /tmp/silverlight-flag


echo ; echo ; echo ; echo 'All Done' ; sleep 2
"

    if [[ -e "/tmp/silverlight-flag" ]] ; then
        rm -f /tmp/silverlight-flag
        exit 0
    else
        # failed status if we don't have the flag
        exit 1
    fi
}

#
#  MAIN
#
main "$@"

# vim: set foldmethod=marker :
